enum MessageKey {
	ERR_UNKNOWN,
	ERR_ONLY_IN_SERVER,
	ERR_ONLY_IN_THREAD,
	ERR_ONLY_THREAD_OWNER,
	ERR_NO_EFFECT,
	ERR_PARAMETER_MISSING,
	ERR_INSUFFICIENT_PERMS,
	ERR_CHANNEL_VISIBILITY,
	ERR_CHANNEL_SLOWMODE,
	ERR_AMBIGUOUS_THREAD_AUTHOR,

	SUCCESS_THREAD_CREATE,
	SUCCESS_THREAD_ARCHIVE_IMMEDIATE,
	SUCCESS_THREAD_ARCHIVE_SLOW,
}

export default MessageKey;
